**This notebook covers work on 3 variable linear system equations**

In [11]:
# let's start by importing the required libraries

import numpy as np
import copy

In [3]:
# let's define a 2d array with 3 variables

eq_arr = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

# let's define a 1d array with results from eq array

res_arr = np.array([-10, 0, 17], dtype=np.dtype(float))

# let's print the matrices

print(f"Equation Matrix: \n {eq_arr} \n")
print(f"Result Matrix: \n {res_arr} \n")

Equation Matrix: 
 [[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]] 

Result Matrix: 
 [-10.   0.  17.] 



In [5]:
# now let's check out the shape of matrices and derive dimension

sh_eq_arr = eq_arr.shape
sh_res_arr = res_arr.shape

print(f"Shape of Equation Matrix: \n {sh_eq_arr} \n")
print(f"Shape of Result Matrix: \n {sh_res_arr} \n")

ndim_eq_arr = np.ndim(eq_arr)
ndim_res_arr = np.ndim(res_arr)

print(f"Dimensions of Equation Matrix: \n {ndim_eq_arr} \n")
print(f"Dimensions of Result Matrix: \n {ndim_res_arr} \n")

Shape of Equation Matrix: 
 (3, 3) 

Shape of Result Matrix: 
 (3,) 

Dimensions of Equation Matrix: 
 2 

Dimensions of Result Matrix: 
 1 



In [6]:
# now let's use linear algebra function to solve the linear equation

sol_arr = np.linalg.solve(eq_arr, res_arr)

print(f"Solution of the linear equation is: {sol_arr}")

Solution of the linear equation is: [ 1.  4. -2.]


In [8]:
# now let's use linear algebra function to derive the determinant of the linear equation

det_arr = np.linalg.det(eq_arr)

print(f"Determinant of the linear equation is: {det_arr:0.2f}")

Determinant of the linear equation is: -60.00


In [10]:
# now let's reshape the arrays and stack them together to prepare them for row reduction

stck_eq_arr = np.hstack((eq_arr,res_arr.reshape(3,1)))

print(f"Restacked array is: {stck_eq_arr}")


Restacked array is: [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


In [27]:
# now let's define 3 specific functions to support our reduced row echelon form

# let's start with multiple of a scalar for a particular row

def multiply_row(orig_arr, row_index, multiple_scalar):
    cp_orig_arr = np.copy(orig_arr)
    cp_orig_arr[row_index] = orig_arr[row_index] * multiple_scalar
    return cp_orig_arr

In [28]:
# now let's print the original and modified array after scalar multiple

print(f"Original array is: \n {stck_eq_arr} \n")
mod_eq_arr = multiply_row(stck_eq_arr, 1, 2)
print(f"Modified array after change is: \n {mod_eq_arr} \n")

Original array is: 
 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]] 

Modified array after change is: 
 [[  4.  -3.   1. -10.]
 [  4.   2.   6.   0.]
 [ -1.   2.  -5.  17.]] 



In [29]:
# now let's do addition of two rows and add option for scalar multiple as well

def add_rows(orig_arr, row_index_1, row_index_2, multiple_scalar):
    cp_orig_arr = np.copy(orig_arr)
    cp_orig_arr[row_index_2] = multiple_scalar * orig_arr[row_index_1] + orig_arr[row_index_2]
    return cp_orig_arr

In [30]:
# now let's print the original and modified array after addition and scalar multiple

print(f"Original array is: \n {stck_eq_arr} \n")
mod_eq_arr = add_rows(stck_eq_arr, 2, 1, 2)
print(f"Modified array after change is: \n {mod_eq_arr} \n")

Original array is: 
 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]] 

Modified array after change is: 
 [[  4.  -3.   1. -10.]
 [  0.   5.  -7.  34.]
 [ -1.   2.  -5.  17.]] 



In [31]:
# now let's do another function to swap two rows

def swap_rows(orig_arr, row_index_1, row_index_2):
    cp_orig_arr = np.copy(orig_arr)
    cp_orig_arr[[row_index_1,row_index_2]] = cp_orig_arr[[row_index_2,row_index_1]]
    return cp_orig_arr

In [32]:
# now let's print the original and modified array after swapping rows

print(f"Original array is: \n {stck_eq_arr} \n")
mod_eq_arr = swap_rows(stck_eq_arr, 2, 1)
print(f"Modified array after change is: \n {mod_eq_arr} \n")

Original array is: 
 [[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]] 

Modified array after change is: 
 [[  4.  -3.   1. -10.]
 [ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]] 

