**This notebook will cover matrix multiplication operations**

In [2]:
# import the libraries

import numpy as np

In [3]:
# let's define sample data set

A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix A (3 by 3):\n", A)

B = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix B (3 by 2):\n", B)

Matrix A (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]


In [4]:
dot_prod = np.dot(A,B)
matr_mult = np.matmul(A, B)

print(f"Dot product of the matrices is: {dot_prod}")
print(f"Matrix multiplication of the matrices is: {matr_mult}")

Dot product of the matrices is: [[ 89 107]
 [ 47  49]
 [ 40  44]]
Matrix multiplication of the matrices is: [[ 89 107]
 [ 47  49]
 [ 40  44]]


In [10]:
# now let's reverse the matrices and try to calculate dot product and multiplication again

try:
    dot_prod = np.dot(B,A)
    print(f"Dot product of the matrices is: {dot_prod}")
except ValueError as err:
    print(err)

try:
    matr_mult = np.matmul(B, A)
    print(f"Matrix multiplication of the matrices is: {matr_mult}")
except ValueError as err:
    print(err)

shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [7]:
# now let's try subtraction from matrice

result = A - 3 
print(f"Reduced matrice is : {result}")

Reduced matrice is : [[ 1  6  6]
 [ 6 -2  3]
 [ 6 -1  0]]
