In [3]:
import numpy as np

# Numpy arrays are more compact in storage and efficient in processing than Python lists
# Numpy only store similar data types elements in arrays

one_d_arr = np.array([10,12])

print(f"Numpy one dimensional array example: {one_d_arr}")

Numpy one dimensional array example: [10 12]


**Let's look at different ways to initialize arrays**

In [16]:
# Different ways to create arrays in numpy

# 1 accessing array function and passing it a list of elements
one_d_arr_type1 = np.array([10,12,13,15])

print(f"1. Create arrays using array function np.array([10,12,13,15]): {one_d_arr_type1}")

# 2 accessing arange function and passing it integer and it sets array values starting 0 till the integer provided
one_d_arr_type2 = np.arange(3)

print(f"2. Create arrays using arange function np.arange(3): {one_d_arr_type2}")

# 3 accessing arange function and passing it start integer, end integer and interval
one_d_arr_type3 = np.arange(1,20,3)

print(f"3. Create arrays using arange function np.arange(1,20,3): {one_d_arr_type3}")

# 4 accessing linspace function and passing it starting integer, end integer and number of equal spaced integers to include
one_d_arr_type4 = np.linspace(1,1500,10,dtype=int)

print(f"4. Create arrays using linspace function np.linspace(1,1500,10): {one_d_arr_type4}")

1. Create arrays using array function np.array([10,12,13,15]): [10 12 13 15]
2. Create arrays using arange function np.arange(3): [0 1 2]
3. Create arrays using arange function np.arange(1,20,3): [ 1  4  7 10 13 16 19]
4. Create arrays using linspace function np.linspace(1,1500,10): [   1  167  334  500  667  833 1000 1166 1333 1500]


In [19]:
# Now let's try and create an array of characters

char_arr = np.array(['This is string of characters contained in array of characters'])

print(f"The character array is:{char_arr}")

# Let's detect the data type of the array

print(f"The data type of the character array is: {char_arr.dtype}")

The character array is:['This is string of characters contained in array of characters']
The data type of the character array is: <U61


**Let's look at different ways to instantiate arrays**

In [24]:
# Now let's look at different ways to initiate an array

empty_arr = np.empty(10, dtype=int) # Initiates an empty array with 10 placeholder elements
zeros_arr = np.zeros(10, dtype=int) # Initiates an array with 10 zero value elements
ones_arr  = np.ones(10, dtype=int) # Initiates an array with 10 one value elements
random_arr = np.random.rand(3) # Initiates an array with 3 random numbers from 0 to 1

# Empty array contains inital value from memory location where that array is allocated
print(f"1. Printing empty array: {empty_arr}") 

print(f"2. Printing zeros array: {zeros_arr}")
print(f"3. Printing ones array: {ones_arr}")
print(f"4. Printing random array: {random_arr}")


1. Printing empty array: [1 1 1 1 1 1 1 1 1 1]
2. Printing zeros array: [0 0 0 0 0 0 0 0 0 0]
3. Printing ones array: [1 1 1 1 1 1 1 1 1 1]
4. Printing random array: [0.78585963 0.30374588 0.2388243 ]


**Now let's look at multidimensional arrays**

In [9]:
# First let's create a two dimensional array

# one simple way to create is below
two_d_arr = np.array([[1,2,3],[300,500,700]])
print(f"This is a simple example of a 2 D array: {two_d_arr}")

# another way to create is by reshaping an existing one dim array into two dim array
one_d_arr = np.array([1,2,3,4])
two_d_arr_res = np.reshape(one_d_arr, (4,1)) # here 2,3 is the dimensions or in other words number of rows and columns of new array

print(f"This is another way to create two d array by reshaping one d array: {two_d_arr_res}")

This is a simple example of a 2 D array: [[  1   2   3]
 [300 500 700]]
This is another way to create two d array by reshaping one d array: [[1]
 [2]
 [3]
 [4]]


In [13]:
# Now let's try to fetch a few properties of the multi dimension array which is by default of type ndarray when initialized

mul_dim_arr = np.array([[1,2,3],[300,500,700],[500,700,900]])
mul_dim_arr_shap = mul_dim_arr.shape
mul_dim_arr_ndim = mul_dim_arr.ndim
mul_dim_arr_size = mul_dim_arr.size

print(f"The size of the multi dimension array is: {mul_dim_arr_size}")
print(f"The shape of the multi dimension array is: {mul_dim_arr_shap}")
print(f"The number of dimensions of the multi dimension array is: {mul_dim_arr_ndim}")

The size of the multi dimension array is: 9
The shape of the multi dimension array is: (3, 3)
The number of dimensions of the multi dimension array is: 2


**Now let's look at some array math operations**

In [16]:
# Let's initialize two one d arrays
one_d_arr_1 = np.array([1,2,3])
one_d_arr_2 = np.array([4,5,6])

# adding both arrays
addition_arr = one_d_arr_1 + one_d_arr_2
print(f"Addition of two one d arrays is: {addition_arr}")

# subtracting both arrays
subtraction_arr = one_d_arr_2 - one_d_arr_1
print(f"Subtraction of two one d arrays is: {subtraction_arr}")

# multiplication of both arrays
multiplication_arr = one_d_arr_1 * one_d_arr_2
print(f"Multiplication of two one d arrays is: {multiplication_arr}")

# arrays can also be multiplied by single scalar values
mult_ex_2_arr = one_d_arr_1 * 3
print(f"Multiplication of one d arrays with a scalar 3 is: {mult_ex_2_arr}")

Addition of two one d arrays is: [5 7 9]
Subtraction of two one d arrays is: [3 3 3]
Multiplication of two one d arrays is: [ 4 10 18]
Multiplication of one d arrays with a scalar 3 is: [3 6 9]


**Now let's understand the indexing process in arrays**

In [23]:
# let's search an array by a specific index, in this case a one d array
one_d_arr = np.array([1,3,4,64,3,6,2,2])
index_of_5 = one_d_arr[5]
print(f"Element at index 5 in one d array is: {index_of_5}")

two_d_arr = np.array([[1,3,2,4,5,6],[53,43,23,43,45,56],[233,3232,23,1323,44,424]])
index_of_3_4 = two_d_arr[2,4]
print(f"Element at index 5 in one d array is: {two_d_arr}")
                     

Element at index 5 in one d array is: 6
Element at index 5 in one d array is: [[   1    3    2    4    5    6]
 [  53   43   23   43   45   56]
 [ 233 3232   23 1323   44  424]]


**Now let's understand the concept of slicing an array**

In [48]:

# Initialize a one d array
arr_one_d = np.array([1,3,4,5,61,3,3,4,5])

# slice when start and end of the index are given
slice_one_d_arr = arr_one_d[3:5]
print(f"Sliced version of one d array from 3 to 5 index is: {slice_one_d_arr}")

# slice when start is given and end of the index is not given, it assumes end value is n-1
slice_one_d_arr = arr_one_d[2:]
print(f"Sliced version of one d array from 2 to end of index is: {slice_one_d_arr}")

# slice when start is not given and end of the index is given, it assumes start is 0th element
slice_one_d_arr = arr_one_d[:7]
print(f"Sliced version of one d array from 0 to 7 is: {slice_one_d_arr}")

# slice when start is given and end of the index is given, and step is given
slice_one_d_arr = arr_one_d[0:9:2]
print(f"Sliced version of one d array from 0 to 9 with step of 2 is: {slice_one_d_arr}")

# slice when start and end of the index is not given, and step is given
slice_one_d_arr = arr_one_d[::2]
print(f"Sliced version of one d array when start and end is not given and step is 2: {slice_one_d_arr}")

# when start is not given, end is not given and step is not given, in either of the cases array will be equal to original
print(arr_one_d == arr_one_d[:])
print(arr_one_d == arr_one_d[::])

# Now let's test the slicing on a two dimensional array
two_d_arr = ([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]])
slice_two_d_arr = two_d_arr[1:2]
print(f"Slicing of a two d array produces: {slice_two_d_arr}")

# Now let's test the slicing on a two dimensional array when only step is given
two_d_arr = ([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]])
slice_two_d_arr = two_d_arr[::2]
print(f"Slicing of a two d array produces: {slice_two_d_arr}")

# Now let's test the slicing on a two dimensional array and extracting a specific column, 1 below
two_d_arr = np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]])
slice_two_d_arr = two_d_arr[:,1]
print(f"Slicing of a two d array produces: {slice_two_d_arr}")

Sliced version of one d array from 3 to 5 index is: [ 5 61]
Sliced version of one d array from 2 to end of index is: [ 4  5 61  3  3  4  5]
Sliced version of one d array from 0 to 7 is: [ 1  3  4  5 61  3  3]
Sliced version of one d array from 0 to 9 with step of 2 is: [ 1  4 61  3  5]
Sliced version of one d array when start and end is not given and step is 2: [ 1  4 61  3  5]
[ True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True]
Slicing of a two d array produces: [[5, 6, 7, 8, 9]]
Slicing of a two d array produces: [[1, 2, 3, 4, 5], [10, 11, 12, 13, 14]]
Slicing of a two d array produces: [ 2  6 11]


**Now let's understand the concept of stacking arrays**

In [57]:
one_d_arr_1 = np.array([1,3,4])
one_d_arr_2 = np.array([4,5,6])

one_d_arr_hstack = np.hstack((one_d_arr_1,one_d_arr_2))
print(f"Horizontal stacking of one d array is: {one_d_arr_hstack}")

one_d_arr_vstack = np.vstack((one_d_arr_1,one_d_arr_2))
print(f"Vertical stacking of one d array is: {one_d_arr_vstack}")

two_d_arr_1 = np.array([[1,3,4],[5,6,7]])
two_d_arr_2 = np.array([[200,300,400],[600,700,900]])

two_d_arr_hstack = np.hstack((two_d_arr_1,two_d_arr_2))
print(f"Horizontal stacking of two d array is: {two_d_arr_hstack}")

two_d_arr_vstack = np.vstack((two_d_arr_1,two_d_arr_2))
print(f"Vertical stacking of two d array is: {two_d_arr_vstack}")


Horizontal stacking of one d array is: [1 3 4 4 5 6]
Vertical stacking of one d array is: [[1 3 4]
 [4 5 6]]
Horizontal stacking of two d array is: [[  1   3   4 200 300 400]
 [  5   6   7 600 700 900]]
Vertical stacking of two d array is: [[  1   3   4]
 [  5   6   7]
 [200 300 400]
 [600 700 900]]
